services:
  - type: web
    name: trustshield-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npx prisma migrate deploy && npm run seed
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        scope: project
      - key: JWT_SECRET
        scope: project
      - key: FRONTEND_URL
        scope: project
